name: newsfeed_mobile
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^3.0.3
  provider: ^4.0.1
  moor_flutter: ^2.0.0
  webview_flutter: ^0.3.15+1
  flutter_markdown: ^0.3.3
  shimmer: ^1.0.1
  transparent_image: ^1.0.0
  progress_indicators: ^0.1.4
  bubble_tab_indicator: "^0.1.4"
  url_launcher: ^5.2.5
  sliding_up_panel: ^0.3.6
  flutter_staggered_grid_view: ^0.3.0
  random_color: ^1.0.3
  path_provider: ^1.6.1
  sembast: ^2.1.3
  debounce_throttle: ^1.1.0
  shared_preferences: ^0.5.4+5
  responsive_scaffold: ^1.3.0+2
  modal_progress_hud: ^0.1.3
  flutter_easyrefresh: ^2.0.9
  json_schema_form: ^0.8.0
  shared_preferences_macos:

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  flutter_slidable: "^0.5.4"
  firebase_core: ^0.4.3+1
  firebase_dynamic_links: ^0.5.0+9
  liquid_pull_to_refresh: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mockito: ^4.1.1
  flutter_driver:
    sdk: flutter
  test: any
  moor_generator: # use the latest versions
  build_runner:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/search-by-algolia-dark-background.png
    - assets/code.gif
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

module:
  androidX: true
